# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3438c81a6175cd161ea2c359504bbc23bd101f9db8be5978e6c2e0f650af8cecea266ca17f0546dd439feb5ca5a531643c08a4b00d63ca37e677ecd7521ded1

test:
  secret_key_base: df9e17a8358a5a9b3ae9dca65a2e307979131a83e06fac284d584178682a772999983ea52feb033ea7c55be7623504d02a25cb3d65ab6316152daeff523a7647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
